server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://kafka-docker:5432/recognizer?stringtype=unspecified
    username: admin
    password: No4Nooxip4qu
    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create

n_gram_size: 3
max_n_gram_size: 500
